### ISSUE TITLE
category_concepts.json

### ISSUE THREAD

**Issue by hss121** [PKU-ICST-MIPL/MKVSE-TOMM2023#1]
Hello, I am interested in your work. During the reproduction process, I noticed that you used the file "category_concepts.json", but did not provide the corresponding specific content. Would you mind providing this information? Thank you very much for your help!

**Comment by FDD-github** [comment]
I'm glad you can pay attention to our work. We follow CVSE to generate the 300 concepts, and you can find the github link of CVSE [1] in our README.md. 

[1] https://github.com/BruceW91/CVSE

**Comment by lijianing0422** [comment]
I couldn't find the /f30k/Concept_annotations/concepts_300.pkl file when training MGCN.Looking forward to replying！
